on:
  push:
    branches-ignore:
      - '**.tmp'

name: build

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        machine:
          - qemux86
          - qemux86-64
          - qemuarm
          - qemuarm64
          - qemumips

    steps:
      - name: Checkout poky
        run: |
          git clone --depth 1 git://git.yoctoproject.org/poky.git .
      - name: Checkout meta-rust
        uses: actions/checkout@v2
        with:
          path: meta-rust
      - name: Checkout meta-openembedded
        run: |
          git clone --depth 1 git://git.openembedded.org/meta-openembedded.git meta-openembedded
      - name: install buildtools
        run: ./scripts/install-buildtools
      - name: install other build tools
        run: apt install diffstat
      - name: build
        run: ./meta-rust/scripts/build2
        env:
          MACHINE: ${{ matrix.machine }}
